from __future__ import annotations


SEED_DATE = "2026-07-02"


COMPANIES = [
    {
        "company_name": "Fresnillo plc",
        "ticker": "FRES",
        "exchange": "LSE",
        "country": "United Kingdom / Mexico",
        "sector": "Precious Metals",
        "industry": "Silver and gold mining",
        "business_summary": "London-listed precious metals miner with operations in Mexico, focused on silver and gold.",
        "investment_thesis": "Offers direct silver and gold exposure through a major primary silver producer.",
        "reasons_we_like_it": "Strong fit with precious metals preference; large silver exposure; London listing.",
        "reasons_for_caution": "Operational execution, ore grades, energy costs, and Mexico country risk can affect results.",
        "potential_risks": "Commodity price volatility; mine safety; regulatory changes; cost inflation.",
        "primary_products": "Silver, gold, lead, zinc",
        "website": "https://www.fresnilloplc.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": "Public reports reviewed during seeding noted lower quarterly silver output while full-year guidance was maintained.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.fresnilloplc.com; https://www.wsj.com/business/fresnillos-quarterly-silver-production-slips-6b71ccba",
    },
    {
        "company_name": "Antofagasta plc",
        "ticker": "ANTO",
        "exchange": "LSE",
        "country": "United Kingdom / Chile",
        "sector": "Copper",
        "industry": "Copper mining",
        "business_summary": "London-listed copper miner with core mining operations in Chile.",
        "investment_thesis": "Quality copper exposure linked to electrification, grids, infrastructure, and industrial demand.",
        "reasons_we_like_it": "Pure copper focus; FTSE 100 liquidity; strong long-term copper theme.",
        "reasons_for_caution": "Valuation can move sharply with copper prices and Chilean operating conditions.",
        "potential_risks": "Copper price volatility; water availability; permitting; project delivery.",
        "primary_products": "Copper, molybdenum, gold, silver",
        "website": "https://www.antofagasta.co.uk",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": "Recent public market coverage highlighted share-price volatility after a strong copper-led run.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.antofagasta.co.uk; https://www.marketwatch.com/data-news/antofagasta-climbs-tuesday-outperforms-market-6b9e9bb9-3eb06c958731",
    },
    {
        "company_name": "Endeavour Mining plc",
        "ticker": "EDV",
        "exchange": "LSE",
        "country": "United Kingdom / West Africa",
        "sector": "Gold",
        "industry": "Gold mining",
        "business_summary": "Gold producer with operations focused in West Africa, including Senegal, Cote d'Ivoire, and Burkina Faso.",
        "investment_thesis": "African gold exposure with scale and organic resource-growth ambitions.",
        "reasons_we_like_it": "Strong gold fit; Africa priority; producer rather than early-stage explorer.",
        "reasons_for_caution": "Political and security risks are higher than in many developed markets.",
        "potential_risks": "Jurisdiction risk; mine disruption; gold price volatility; cost inflation.",
        "primary_products": "Gold",
        "website": "https://www.endeavourmining.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": "Public reporting noted a multi-year exploration plan targeting significant new gold resources.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.endeavourmining.com; https://www.wsj.com/business/endeavour-mining-targets-discovery-of-up-to-15-million-ounces-of-resources-over-next-5-years-f44dcc2f",
    },
    {
        "company_name": "KGHM Polska Miedz S.A.",
        "ticker": "KGH",
        "exchange": "WSE",
        "country": "Poland",
        "sector": "Copper",
        "industry": "Copper and silver mining",
        "business_summary": "Polish copper and silver producer with mining and smelting operations.",
        "investment_thesis": "European copper and silver exposure aligned with electrification and precious metals themes.",
        "reasons_we_like_it": "Copper plus silver combination; European strategic materials angle.",
        "reasons_for_caution": "Energy costs, taxes, and European industrial policy can affect margins.",
        "potential_risks": "Commodity prices; power costs; currency; regulatory and tax changes.",
        "primary_products": "Copper, silver, precious metals",
        "website": "https://kghm.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://kghm.com",
    },
    {
        "company_name": "Rio Tinto Group",
        "ticker": "RIO",
        "exchange": "LSE",
        "country": "United Kingdom / Australia",
        "sector": "Mining",
        "industry": "Diversified mining",
        "business_summary": "Global diversified miner producing iron ore, aluminium, copper, lithium, and industrial minerals.",
        "investment_thesis": "Large-scale exposure to materials needed for infrastructure and energy transition.",
        "reasons_we_like_it": "Scale, asset quality, copper and lithium optionality, strong UK listing access.",
        "reasons_for_caution": "Iron ore remains a major driver and can dilute copper/clean-energy exposure.",
        "potential_risks": "China demand; commodity cycles; permitting; environmental and social license.",
        "primary_products": "Iron ore, aluminium, copper, lithium, borates",
        "website": "https://www.riotinto.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": "Public coverage focused on power-cost pressure for Australian aluminium smelting and the strategic need for affordable clean power.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.riotinto.com; https://www.news.com.au/finance/business/manufacturing/labor-confident-on-tomago-smelter-deal-as-talks-drags-on/news-story/cc132272a18c18f0b6ace1f9bf306d7d",
    },
    {
        "company_name": "Anglo American plc",
        "ticker": "AAL",
        "exchange": "LSE",
        "country": "United Kingdom / South Africa",
        "sector": "Mining",
        "industry": "Diversified mining",
        "business_summary": "Global miner with exposure to copper, iron ore, diamonds, crop nutrients, and platinum group metals.",
        "investment_thesis": "Strategic mining exposure with South African heritage and material copper optionality.",
        "reasons_we_like_it": "Africa connection; copper and PGMs; major London-listed resource company.",
        "reasons_for_caution": "Portfolio complexity and restructuring can obscure near-term value.",
        "potential_risks": "Commodity cycles; South Africa power/logistics; restructuring execution; diamond market weakness.",
        "primary_products": "Copper, iron ore, diamonds, PGMs, crop nutrients",
        "website": "https://www.angloamerican.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.angloamerican.com",
    },
    {
        "company_name": "Glencore plc",
        "ticker": "GLEN",
        "exchange": "LSE",
        "country": "Switzerland / United Kingdom",
        "sector": "Mining",
        "industry": "Diversified mining and commodities marketing",
        "business_summary": "Diversified natural resources group with mining, processing, recycling, and commodity marketing activities.",
        "investment_thesis": "Transition-metals exposure, especially copper, cobalt, zinc, and nickel, with cash-generating marketing operations.",
        "reasons_we_like_it": "Copper expansion potential; global scale; commodity supply-chain intelligence.",
        "reasons_for_caution": "Coal exposure and marketing complexity create governance and ESG caution.",
        "potential_risks": "Commodity cycles; regulatory scrutiny; coal transition risk; leverage to global trade.",
        "primary_products": "Copper, cobalt, zinc, nickel, coal, oil marketing",
        "website": "https://www.glencore.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Moderate",
        "latest_news_summary": "Recent public market commentary highlighted Glencore cash generation and copper expansion, alongside portfolio debate.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.glencore.com; https://www.wsj.com/business/basic-materials-roundup-market-talk-9ed0c08f",
    },
    {
        "company_name": "Boliden AB",
        "ticker": "BOL",
        "exchange": "Nasdaq Stockholm",
        "country": "Sweden",
        "sector": "Mining",
        "industry": "Base metals mining and smelting",
        "business_summary": "Nordic metals company mining and smelting copper, zinc, nickel, lead, gold, and silver.",
        "investment_thesis": "European base-metals platform exposed to copper and zinc demand.",
        "reasons_we_like_it": "European strategic materials exposure; integrated mining and smelting.",
        "reasons_for_caution": "Smelters are energy intensive and sensitive to treatment charges.",
        "potential_risks": "Power costs; mine grades; environmental liabilities; metal prices.",
        "primary_products": "Copper, zinc, nickel, lead, gold, silver",
        "website": "https://www.boliden.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.boliden.com",
    },
    {
        "company_name": "Sibanye Stillwater Ltd",
        "ticker": "SSW",
        "exchange": "JSE",
        "country": "South Africa",
        "sector": "Precious Metals",
        "industry": "PGM and gold mining",
        "business_summary": "South African mining group producing platinum group metals, gold, and battery metals, with recycling exposure.",
        "investment_thesis": "Africa-priority precious metals and recycling exposure with leverage to platinum group metals.",
        "reasons_we_like_it": "South Africa exposure; PGMs; circular economy angle.",
        "reasons_for_caution": "PGM markets can be weak when auto demand softens.",
        "potential_risks": "Labour relations; power supply; PGM prices; balance sheet pressure.",
        "primary_products": "Platinum, palladium, rhodium, gold, battery metals",
        "website": "https://www.sibanyestillwater.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.sibanyestillwater.com",
    },
    {
        "company_name": "CRH plc",
        "ticker": "CRH",
        "exchange": "LSE",
        "country": "Ireland",
        "sector": "Construction",
        "industry": "Building materials",
        "business_summary": "Global building materials group supplying aggregates, cement, asphalt, concrete, and infrastructure products.",
        "investment_thesis": "Infrastructure and construction exposure with durable materials demand.",
        "reasons_we_like_it": "Infrastructure priority; scale; cash-generative materials business.",
        "reasons_for_caution": "North American exposure is large, so geographic fit is less pure.",
        "potential_risks": "Construction cycles; energy costs; emissions regulation; acquisition execution.",
        "primary_products": "Aggregates, cement, asphalt, ready-mix concrete",
        "website": "https://www.crh.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.crh.com",
    },
    {
        "company_name": "Balfour Beatty plc",
        "ticker": "BBY",
        "exchange": "LSE",
        "country": "United Kingdom",
        "sector": "Infrastructure",
        "industry": "Infrastructure construction",
        "business_summary": "UK-headquartered infrastructure group delivering transport, power, water, and social infrastructure projects.",
        "investment_thesis": "Direct UK infrastructure and construction exposure.",
        "reasons_we_like_it": "Strong UK fit; infrastructure backlog; practical real-economy activity.",
        "reasons_for_caution": "Contracting margins can be thin and project risk can surprise.",
        "potential_risks": "Project overruns; public spending cycles; labour and materials inflation.",
        "primary_products": "Infrastructure construction, support services, investments",
        "website": "https://www.balfourbeatty.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.balfourbeatty.com",
    },
    {
        "company_name": "Vinci SA",
        "ticker": "DG",
        "exchange": "Euronext Paris",
        "country": "France",
        "sector": "Infrastructure",
        "industry": "Concessions and construction",
        "business_summary": "French infrastructure group active in concessions, energy, roads, airports, and construction.",
        "investment_thesis": "Long-duration infrastructure and concessions exposure in Europe and globally.",
        "reasons_we_like_it": "Infrastructure cash flows; European focus; diversified concessions.",
        "reasons_for_caution": "Airport and concession traffic can be sensitive to regulation and travel cycles.",
        "potential_risks": "Regulatory intervention; project delivery; debt rates; traffic volumes.",
        "primary_products": "Motorway concessions, airports, construction, energy services",
        "website": "https://www.vinci.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.vinci.com",
    },
    {
        "company_name": "ACS Actividades de Construccion y Servicios SA",
        "ticker": "ACS",
        "exchange": "BME",
        "country": "Spain",
        "sector": "Construction",
        "industry": "Construction and infrastructure",
        "business_summary": "Spanish infrastructure and construction group with global civil engineering, concessions, and services operations.",
        "investment_thesis": "European construction platform with global infrastructure exposure.",
        "reasons_we_like_it": "Infrastructure fit; strong international footprint; civil works expertise.",
        "reasons_for_caution": "Complex group structure and project execution risk.",
        "potential_risks": "Contract risk; leverage; construction cycle; political/public contract exposure.",
        "primary_products": "Civil construction, concessions, engineering services",
        "website": "https://www.grupoacs.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.grupoacs.com",
    },
    {
        "company_name": "Heidelberg Materials AG",
        "ticker": "HEI",
        "exchange": "Xetra",
        "country": "Germany",
        "sector": "Construction",
        "industry": "Cement and building materials",
        "business_summary": "Global building materials producer focused on cement, aggregates, ready-mixed concrete, and asphalt.",
        "investment_thesis": "European materials exposure tied to infrastructure, construction, and low-carbon cement transition.",
        "reasons_we_like_it": "Construction fit; decarbonisation optionality; essential materials.",
        "reasons_for_caution": "Cement is energy intensive and carbon intensive.",
        "potential_risks": "Carbon costs; energy prices; construction downturns; regulatory pressure.",
        "primary_products": "Cement, aggregates, ready-mixed concrete, asphalt",
        "website": "https://www.heidelbergmaterials.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.heidelbergmaterials.com",
    },
    {
        "company_name": "National Grid plc",
        "ticker": "NG",
        "exchange": "LSE",
        "country": "United Kingdom",
        "sector": "Utilities",
        "industry": "Electricity and gas networks",
        "business_summary": "UK-headquartered regulated utility owning electricity and gas transmission and distribution networks.",
        "investment_thesis": "Core grid infrastructure exposure as electrification and data-center demand increase.",
        "reasons_we_like_it": "UK fit; regulated assets; direct grid investment theme.",
        "reasons_for_caution": "Regulatory returns and capital raises can pressure shareholders.",
        "potential_risks": "Regulatory resets; debt costs; execution of grid capex; political pressure on bills.",
        "primary_products": "Electricity transmission, electricity distribution, gas networks",
        "website": "https://www.nationalgrid.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": "Current market theme review highlights grid demand pressure from AI data centers and electrification.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.nationalgrid.com; https://www.itpro.com/infrastructure/data-centres/energy-providers-are-flying-blind-thanks-to-unpredictable-ai-data-center-demands",
    },
    {
        "company_name": "SSE plc",
        "ticker": "SSE",
        "exchange": "LSE",
        "country": "United Kingdom",
        "sector": "Utilities",
        "industry": "Electric utilities and renewables",
        "business_summary": "UK energy company focused on regulated networks and renewable generation.",
        "investment_thesis": "UK clean-energy and grid infrastructure exposure.",
        "reasons_we_like_it": "Strong fit with utilities and clean energy; UK priority.",
        "reasons_for_caution": "Large capex programme and power-price exposure require monitoring.",
        "potential_risks": "Regulatory changes; project delays; wholesale power prices; debt costs.",
        "primary_products": "Electricity networks, wind generation, flexible generation",
        "website": "https://www.sse.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.sse.com",
    },
    {
        "company_name": "Iberdrola SA",
        "ticker": "IBE",
        "exchange": "BME",
        "country": "Spain",
        "sector": "Utilities",
        "industry": "Electric utilities and renewables",
        "business_summary": "Spanish multinational electric utility with networks and renewable generation assets.",
        "investment_thesis": "European clean-energy and regulated-network compounder.",
        "reasons_we_like_it": "Clean energy fit; regulated networks; Europe priority.",
        "reasons_for_caution": "Valuation and debt sensitivity need monitoring.",
        "potential_risks": "Regulation; interest rates; project execution; power prices.",
        "primary_products": "Electricity networks, wind, solar, hydro, retail energy",
        "website": "https://www.iberdrola.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.iberdrola.com",
    },
    {
        "company_name": "Enel SpA",
        "ticker": "ENEL",
        "exchange": "Borsa Italiana",
        "country": "Italy",
        "sector": "Utilities",
        "industry": "Electric utilities",
        "business_summary": "Italian multinational utility active in electricity networks, generation, renewables, and retail energy.",
        "investment_thesis": "Large European utility with renewables and grid exposure.",
        "reasons_we_like_it": "Utilities and clean energy fit; European scale.",
        "reasons_for_caution": "Debt load and regulatory/geographic complexity require care.",
        "potential_risks": "Interest rates; regulation; country exposure; energy prices.",
        "primary_products": "Electricity networks, renewable generation, retail energy",
        "website": "https://www.enel.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.enel.com",
    },
    {
        "company_name": "Orsted A/S",
        "ticker": "ORSTED",
        "exchange": "Nasdaq Copenhagen",
        "country": "Denmark",
        "sector": "Clean Energy",
        "industry": "Offshore wind and renewable energy",
        "business_summary": "Danish renewable energy company best known for offshore wind development and operation.",
        "investment_thesis": "Direct clean-energy exposure with offshore wind expertise.",
        "reasons_we_like_it": "Clean energy leader; Europe priority; real assets.",
        "reasons_for_caution": "Offshore wind economics have been volatile due to rates, supply chain, and contract pricing.",
        "potential_risks": "Project impairments; turbine costs; interest rates; political support changes.",
        "primary_products": "Offshore wind, onshore renewables, bioenergy",
        "website": "https://orsted.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://orsted.com",
    },
    {
        "company_name": "Verbund AG",
        "ticker": "VER",
        "exchange": "Vienna Stock Exchange",
        "country": "Austria",
        "sector": "Clean Energy",
        "industry": "Hydroelectric power",
        "business_summary": "Austrian electricity company with a major hydroelectric generation base.",
        "investment_thesis": "European clean-power exposure through hydro generation and grid-adjacent infrastructure.",
        "reasons_we_like_it": "Clean energy fit; hydro scarcity value; European focus.",
        "reasons_for_caution": "Hydrology and power prices can cause earnings volatility.",
        "potential_risks": "Rainfall variation; regulation; power price swings; valuation.",
        "primary_products": "Hydroelectric power, electricity trading, transmission interests",
        "website": "https://www.verbund.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.verbund.com",
    },
    {
        "company_name": "AstraZeneca plc",
        "ticker": "AZN",
        "exchange": "LSE",
        "country": "United Kingdom",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "business_summary": "UK-listed global biopharmaceutical company focused on oncology, biopharmaceuticals, and rare diseases.",
        "investment_thesis": "High-quality UK healthcare exposure with global scale and deep pipeline.",
        "reasons_we_like_it": "UK priority; healthcare fit; innovation and global revenue base.",
        "reasons_for_caution": "Pipeline setbacks and patent cycles can affect valuation.",
        "potential_risks": "Clinical trial risk; regulation; pricing pressure; patent expiries.",
        "primary_products": "Oncology medicines, cardiovascular medicines, respiratory medicines, rare disease therapies",
        "website": "https://www.astrazeneca.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.astrazeneca.com",
    },
    {
        "company_name": "Novo Nordisk A/S",
        "ticker": "NOVO-B",
        "exchange": "Nasdaq Copenhagen",
        "country": "Denmark",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals",
        "business_summary": "Danish healthcare company focused on diabetes, obesity, rare blood, and endocrine disorders.",
        "investment_thesis": "Global healthcare leader with structural demand from diabetes and obesity treatment.",
        "reasons_we_like_it": "Healthcare fit; Europe priority; strong product leadership.",
        "reasons_for_caution": "Valuation and competition in GLP-1 medicines require discipline.",
        "potential_risks": "Pricing pressure; manufacturing constraints; clinical competition; regulatory scrutiny.",
        "primary_products": "Diabetes medicines, obesity medicines, rare disease therapies",
        "website": "https://www.novonordisk.com",
        "watchlist_priority": "High",
        "investment_philosophy_fit": "Strong",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.novonordisk.com",
    },
    {
        "company_name": "Roche Holding AG",
        "ticker": "ROG",
        "exchange": "SIX Swiss Exchange",
        "country": "Switzerland",
        "sector": "Healthcare",
        "industry": "Pharmaceuticals and diagnostics",
        "business_summary": "Swiss healthcare group active in pharmaceuticals and diagnostics.",
        "investment_thesis": "Defensive European healthcare exposure with diagnostics and pharma breadth.",
        "reasons_we_like_it": "Healthcare fit; diagnostics capability; long-term innovation culture.",
        "reasons_for_caution": "Growth can be uneven as older medicines lose exclusivity.",
        "potential_risks": "Pipeline risk; patent expiries; pricing pressure; currency.",
        "primary_products": "Pharmaceuticals, diagnostics, oncology and immunology medicines",
        "website": "https://www.roche.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.roche.com",
    },
    {
        "company_name": "CSL Limited",
        "ticker": "CSL",
        "exchange": "ASX",
        "country": "Australia",
        "sector": "Healthcare",
        "industry": "Biotechnology",
        "business_summary": "Australian biotechnology company focused on plasma therapies, vaccines, and specialty medicines.",
        "investment_thesis": "Asia-Pacific healthcare exposure with global plasma and vaccine franchises.",
        "reasons_we_like_it": "Healthcare fit; Asia-Pacific priority; specialist global niche.",
        "reasons_for_caution": "Plasma collection economics and R&D execution matter.",
        "potential_risks": "Collection costs; regulation; currency; product concentration.",
        "primary_products": "Plasma therapies, vaccines, specialty medicines",
        "website": "https://www.csl.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.csl.com",
    },
    {
        "company_name": "International Consolidated Airlines Group SA",
        "ticker": "IAG",
        "exchange": "LSE",
        "country": "United Kingdom / Spain",
        "sector": "Airlines",
        "industry": "Air passenger transport",
        "business_summary": "Airline group owning British Airways, Iberia, Aer Lingus, Vueling, and LEVEL.",
        "investment_thesis": "European airline exposure with strong brands and transatlantic network leverage.",
        "reasons_we_like_it": "UK/Europe fit; travel recovery and disciplined capacity can support earnings.",
        "reasons_for_caution": "Airlines are cyclical and fuel sensitive.",
        "potential_risks": "Jet fuel prices; labour disruption; demand shocks; regulation and airport constraints.",
        "primary_products": "Passenger flights, cargo, airline loyalty programmes",
        "website": "https://www.iairgroup.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Moderate",
        "latest_news_summary": "Public industry coverage warned that higher jet fuel costs may pressure airline margins and fares.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.iairgroup.com; https://www.theguardian.com/business/2026/jun/07/air-fare-rises-inevitable-as-airlines-face-extra-100bn-jet-fuel-bill-this-year",
    },
    {
        "company_name": "Ryanair Holdings plc",
        "ticker": "RYA",
        "exchange": "Euronext Dublin",
        "country": "Ireland",
        "sector": "Airlines",
        "industry": "Low-cost airline",
        "business_summary": "European low-cost airline group operating short-haul routes across Europe and nearby regions.",
        "investment_thesis": "Low-cost European airline model with scale advantages.",
        "reasons_we_like_it": "Europe priority; cost discipline; travel demand leverage.",
        "reasons_for_caution": "Airline cyclicality and customer/regulatory friction are persistent.",
        "potential_risks": "Fuel prices; aircraft delivery delays; labour; consumer downturn.",
        "primary_products": "Low-cost passenger flights, ancillary travel services",
        "website": "https://www.ryanair.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Moderate",
        "latest_news_summary": "Industry news reviewed during seeding highlighted fuel-cost pressure across airlines.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.ryanair.com; https://www.theguardian.com/business/2026/jun/07/air-fare-rises-inevitable-as-airlines-face-extra-100bn-jet-fuel-bill-this-year",
    },
    {
        "company_name": "Singapore Airlines Limited",
        "ticker": "C6L",
        "exchange": "SGX",
        "country": "Singapore",
        "sector": "Airlines",
        "industry": "International airline",
        "business_summary": "Singapore flag carrier with premium long-haul passenger and cargo operations.",
        "investment_thesis": "Asia-priority airline exposure with a premium brand and hub advantage.",
        "reasons_we_like_it": "Asia fit; high-quality airline franchise; cargo and premium travel exposure.",
        "reasons_for_caution": "Long-haul airlines remain sensitive to fuel, geopolitics, and demand shocks.",
        "potential_risks": "Fuel prices; airspace disruption; tourism cycles; currency.",
        "primary_products": "Passenger flights, cargo, airline services",
        "website": "https://www.singaporeair.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": "Industry news reviewed during seeding highlighted higher fuel costs and route disruption as key airline risks.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.singaporeair.com; https://www.theguardian.com/business/2026/jun/07/air-fare-rises-inevitable-as-airlines-face-extra-100bn-jet-fuel-bill-this-year",
    },
    {
        "company_name": "JD Sports Fashion plc",
        "ticker": "JD",
        "exchange": "LSE",
        "country": "United Kingdom",
        "sector": "Sports",
        "industry": "Sports fashion retail",
        "business_summary": "UK-based global sports fashion and footwear retailer.",
        "investment_thesis": "UK sports-consumer exposure with global retail scale.",
        "reasons_we_like_it": "Sports fit; UK priority; youth and athleisure demand.",
        "reasons_for_caution": "Retail cycles and inventory mistakes can hurt margins.",
        "potential_risks": "Consumer slowdown; brand supplier concentration; inventory; FX.",
        "primary_products": "Sports footwear, apparel, accessories",
        "website": "https://www.jdplc.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.jdplc.com",
    },
    {
        "company_name": "adidas AG",
        "ticker": "ADS",
        "exchange": "Xetra",
        "country": "Germany",
        "sector": "Sports",
        "industry": "Sportswear",
        "business_summary": "German sportswear company designing and selling footwear, apparel, and accessories.",
        "investment_thesis": "European global sports brand with recovery and product-cycle potential.",
        "reasons_we_like_it": "Sports fit; European priority; global brand strength.",
        "reasons_for_caution": "Brand momentum and inventory management must be monitored.",
        "potential_risks": "Consumer demand; competition; China exposure; FX.",
        "primary_products": "Sports footwear, apparel, accessories",
        "website": "https://www.adidas-group.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.adidas-group.com",
    },
    {
        "company_name": "ASICS Corporation",
        "ticker": "7936",
        "exchange": "Tokyo Stock Exchange",
        "country": "Japan",
        "sector": "Sports",
        "industry": "Sportswear and athletic footwear",
        "business_summary": "Japanese sportswear company known for performance running shoes and athletic products.",
        "investment_thesis": "Asia-priority sports brand with performance-running credibility.",
        "reasons_we_like_it": "Asia fit; sports category; differentiated brand in running.",
        "reasons_for_caution": "Consumer trends and international expansion execution matter.",
        "potential_risks": "Competition; currency; fashion/product-cycle risk; supply chain.",
        "primary_products": "Running shoes, sportswear, athletic equipment",
        "website": "https://corp.asics.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://corp.asics.com",
    },
    {
        "company_name": "Shimano Inc.",
        "ticker": "7309",
        "exchange": "Tokyo Stock Exchange",
        "country": "Japan",
        "sector": "Sports",
        "industry": "Cycling components and sporting goods",
        "business_summary": "Japanese manufacturer of bicycle components, fishing tackle, and rowing equipment.",
        "investment_thesis": "Asia-priority sports infrastructure and cycling exposure with strong niche economics.",
        "reasons_we_like_it": "Sports fit; Asia priority; durable brand and component ecosystem.",
        "reasons_for_caution": "Cycling demand can normalize after boom periods.",
        "potential_risks": "Inventory cycle; consumer demand; currency; competition.",
        "primary_products": "Bicycle components, fishing tackle, rowing equipment",
        "website": "https://www.shimano.com",
        "watchlist_priority": "Medium",
        "investment_philosophy_fit": "Good",
        "latest_news_summary": None,
        "last_updated": SEED_DATE,
        "source_urls": "https://www.shimano.com",
    },
]


THEMES = [
    {
        "theme": "Gold",
        "current_outlook": "Constructive but volatile",
        "confidence": "Medium",
        "summary": "Gold remains strategically relevant as a hedge, but recent public commentary shows sensitivity to real yields, the US dollar, and investor flows.",
        "key_drivers": "Central-bank demand; geopolitical risk; real interest rates; US dollar; ETF flows.",
        "key_risks": "Higher bond yields; stronger US dollar; weaker physical demand; crowded positioning.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.businessinsider.com/gold-price-today-forecast-outlook-etf-interest-rates-sell-off-2026-6",
    },
    {
        "theme": "Silver",
        "current_outlook": "Positive with high volatility",
        "confidence": "Medium",
        "summary": "Silver benefits from precious-metal demand and industrial uses, but mine supply and economic sensitivity make it more volatile than gold.",
        "key_drivers": "Solar demand; electronics; monetary demand; mine supply; gold/silver ratio.",
        "key_risks": "Industrial slowdown; mining cost inflation; sharp risk-off liquidations.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.fresnilloplc.com",
    },
    {
        "theme": "Copper",
        "current_outlook": "Structurally positive",
        "confidence": "High",
        "summary": "Copper is supported by power grids, AI data centers, EVs, renewables, and infrastructure, while supply growth remains difficult.",
        "key_drivers": "Grid expansion; electrification; AI data-center power needs; EVs; constrained mine supply.",
        "key_risks": "China slowdown; mine supply surprises; substitution; global recession.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.businessinsider.com/oil-prices-energy-metals-commodities-inflation-goldman-sachs-iran-war-2026-6",
    },
    {
        "theme": "Rare Earths",
        "current_outlook": "Strategic and policy-sensitive",
        "confidence": "Medium",
        "summary": "Rare earths remain strategically important for magnets, defence, clean energy, and electronics, with supply-chain concentration a persistent risk.",
        "key_drivers": "Permanent magnets; defence demand; EV motors; wind turbines; supply-chain security policy.",
        "key_risks": "China policy shifts; opaque pricing; project execution; environmental permitting.",
        "last_updated": SEED_DATE,
        "source_urls": None,
    },
    {
        "theme": "Construction",
        "current_outlook": "Selective",
        "confidence": "Medium",
        "summary": "Construction demand is supported by infrastructure renewal and energy projects, but rates, labour, and material costs remain headwinds.",
        "key_drivers": "Public infrastructure spending; housing cycles; energy infrastructure; urban renewal.",
        "key_risks": "Higher rates; cost overruns; weak property markets; public budget constraints.",
        "last_updated": SEED_DATE,
        "source_urls": None,
    },
    {
        "theme": "Clean Energy",
        "current_outlook": "Long-term positive, near-term uneven",
        "confidence": "Medium",
        "summary": "Clean energy retains strong long-term demand, but offshore wind and renewables developers face interest-rate, supply-chain, and grid-connection pressure.",
        "key_drivers": "Decarbonisation; grid investment; electrification; energy security; corporate power demand.",
        "key_risks": "Higher rates; permitting delays; supply-chain inflation; policy changes.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.iea.org",
    },
    {
        "theme": "Healthcare",
        "current_outlook": "Defensive growth",
        "confidence": "Medium",
        "summary": "Healthcare offers defensive long-term demand from ageing populations, chronic disease, and innovation, while pricing and pipeline risks remain central.",
        "key_drivers": "Ageing populations; obesity and diabetes demand; oncology; diagnostics; emerging-market access.",
        "key_risks": "Drug pricing pressure; trial failures; patent expiries; regulation.",
        "last_updated": SEED_DATE,
        "source_urls": None,
    },
    {
        "theme": "Airlines",
        "current_outlook": "Cautious",
        "confidence": "Medium",
        "summary": "Passenger demand remains important, but public industry reporting highlights pressure from higher jet fuel costs and geopolitical route disruption.",
        "key_drivers": "Passenger demand; premium travel; cargo; capacity discipline; tourism flows.",
        "key_risks": "Fuel prices; airspace disruption; labour costs; recession; regulation.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.theguardian.com/business/2026/jun/07/air-fare-rises-inevitable-as-airlines-face-extra-100bn-jet-fuel-bill-this-year",
    },
    {
        "theme": "Infrastructure",
        "current_outlook": "Positive",
        "confidence": "High",
        "summary": "Infrastructure is supported by grid upgrades, transport renewal, energy security, and public investment needs.",
        "key_drivers": "Grid bottlenecks; transport investment; energy transition; data centers; public-private partnerships.",
        "key_risks": "Regulatory returns; budget pressure; execution risk; higher financing costs.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.itpro.com/infrastructure/data-centres/energy-providers-are-flying-blind-thanks-to-unpredictable-ai-data-center-demands",
    },
    {
        "theme": "Utilities",
        "current_outlook": "Positive but capital intensive",
        "confidence": "High",
        "summary": "Utilities benefit from electrification and grid demand, but forecasting data-center load and funding network expansion are major challenges.",
        "key_drivers": "AI data centers; electrification; grid reinforcement; regulated asset growth; renewable integration.",
        "key_risks": "Regulatory pressure; customer bill affordability; capex overruns; interest rates.",
        "last_updated": SEED_DATE,
        "source_urls": "https://www.itpro.com/infrastructure/data-centres/energy-providers-are-flying-blind-thanks-to-unpredictable-ai-data-center-demands",
    },
]
